services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URL: mongodb://mongo:27017/deversity
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      VITE_API_URL: http://backend:3000
    ports:
      - 3001:80

  mongo:
    image: mongo
